### ISSUE TITLE
clip 1.0 ?

### ISSUE THREAD

**Issue by teytaud** [UARK-AICV/VLCAP#1]
Thanks for this fantastic work.
The requirements file mentions clip=1.0, but https://pypi.org/project/clip/ mentions versions only up to 0.2.0. So the installation crashes.
Do you have a solution ?
<<
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement clip==1.0 (from -r VLCAP/condaenv.vopj0xmb.requirements.txt (line 29)) (from versions: 0.0.1, 0.1.0, 0.2.0)
ERROR: No matching distribution found for clip==1.0 (from -r VLCAP/condaenv.vopj0xmb.requirements.txt (line 29))
>>

**Comment by Kashu7100** [comment]
Thanks you for your interest. 
Please try installing the clip from the [source](https://github.com/openai/CLIP): 

```bash 
pip install git+https://github.com/openai/CLIP.git
```

I am sorry for the inconvenience.

**Comment by teytaud** [comment]
Thanks a lot! This works :-)
