### ISSUE TITLE
How to change the configs,such as num_epochs and batch_size

### ISSUE THREAD

**Issue by JiangTianyu51147** [UARK-AICV/VLCAP#14]

**Comment by JiangTianyu51147** [comment]
I can't find the configs file, so if I want to change these configs, which files should I edit? thanks! :)

**Comment by Kashu7100** [comment]
Hello, you can check [here](https://github.com/UARK-AICV/VLCAP/blob/199560acba61d5e99a74a266ab13fd88d99c8fbb/src/train.py#L464)!

**Comment by JiangTianyu51147** [comment]
Oh!Thank you very much!It is exactly what I want! :):):)
