### ISSUE TITLE
data Preparation

### ISSUE THREAD

**Issue by chunhuizhang** [UARK-AICV/VLCAP#2]
thanks for this fantastic  work too. 
i am new to the research topic, could you please share some common methods to generate the _c3d video feature file (100*2048)_ and the _lang_feature (100*100 of words)_ and _sent_feature (n_sent * 512)_  if you are convenient

**Comment by Kashu7100** [comment]
Thank you for your interests. 

For the c3d video feature extraction, please refer to this [repo](https://github.com/vhvkhoa/SlowFast). 
For the lang_feature, we apply [CLIP](https://github.com/openai/CLIP) for the center frame of a snippet and extracted top N correlated words from the training vocabulary. 
For the sent_feature, we also use the CLIP but only the text encoder. For each GT sentences, we apply CLIP text encoder to get CLIP embedding features. 

Hope this helps!

**Comment by chunhuizhang** [comment]
many thanks, later i'll have a try

**Comment by yueyue0401** [comment]
For C3D, there are some different architectures: https://github.com/vhvkhoa/SlowFast/blob/master/MODEL_ZOO.md
Could you please share which architecture you used to extract the YouCook2 video feature? Is it possible to share the c3d video feature, lang-feature, and sent-feature files? Thank you so much!

**Comment by Kashu7100** [comment]
@yueyue0401 @chunhuizhang 
We publish the code for our new work: https://github.com/UARK-AICV/VLTinT
In the repo, there are more details about how to extract features. I hope this is helpful to you.
