### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by teytaud** [UARK-AICV/VLCAP#3]
This looks like a simple thing like an argument missing but if you have a suggestion I'm interested.
The command line was << bash scripts/train.sh yc2 true >>.

Traceback (most recent call last):
  File "src/train.py", line 706, in <module>
    main()
  File "src/train.py", line 642, in main
    num_workers=opt.num_workers, pin_memory=opt.pin_memory)
  File "XXX/.conda/envs/videocap/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 270, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "XXX.conda/envs/videocap/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 103, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by chunhuizhang** [comment]
please check your Dataset, which may empty (len == 0) causes the error.

**Comment by teytaud** [comment]
du -ks data/anet/*
16075976        data/anet/anet_c3d
14476240        data/anet/anet_c3d.zip
2404464 data/anet/anet_clip_b16
505216  data/anet/anet_clip_b16.zip

**Comment by Kashu7100** [comment]
The provided features are for the ActivityNet. You need to extract the features for YouCook2 in order to run with the yc2 option. 
Please refer to  https://github.com/UARK-AICV/VLCAP/issues/2 for the feature extraction.

**Comment by JiangTianyu51147** [comment]
I have the same error when I try to train MART model on ActivityNet Captions,but i don't have any way to fix it.What shall I do?If you can give some suggestions I will sincerely thank you！

**Comment by Kashu7100** [comment]
@JiangTianyu51147 Could you tell me more about your situation (what command you run, which dataset you tried, etc.) so that I can help you?

**Comment by JiangTianyu51147** [comment]
I input the command 

`bash scripts/train.sh anet true`
 
and reported an error

**Traceback (most recent call last):
  File "src/train.py", line 684, in <module>
    main()
  File "src/train.py", line 632, in main
    num_workers=opt.num_workers, pin_memory=opt.pin_memory)
  File "/XXX/anaconda3/envs/vlcap/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 270, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/XXX/anaconda3/envs/vlcap/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 103, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0**


I have downloaded env feature and lang feature and my VLCAP folder directory is as follows:

|── cache
|── data
│   └── anet
│       ├── env_c3d
│       ├── lang_feature
│       └── sent_feature
├── densevid_eval
├── scripts
├── src
│   └── rtransformer
└── video_feature

and I have changed `data_path` in `VLCAP/src/rtransformer/recursive_caption_dataset.py` but it still reports the same error.
I don't know what should I do.Thank you very much for your help! :)

**Comment by Kashu7100** [comment]
Can I know what is your current setting in RecursiveCaptionDataset?
num_samples=0 error typically occurs when you have wrong path. 

```python
data_path = {
        "anet": {
            "env_feat": "data/anet/anet_c3d/",
            "clip_feat": "data/anet/anet_clip_b16/lang_feature/",
            "sent_feat": "data/anet/anet_clip_b16/sent_feature/"
        },
        "yc2": {
            "env_feat": "data/yc2/yc2_c3d/",
            "clip_feat": "data/yc2/yc2_clip_b16/lang_feature/",
            "sent_feat": "data/yc2/yc2_clip_b16/sent_feature/"
        }
    }
```

**Comment by JiangTianyu51147** [comment]
This is my setting in `XXX/VLCAP/src/rtransformer/recursive_caption_dataset.py`
```python
data_path = {
        "anet": {
            "env_feat": "XXX/VLCAP/data/anet/env_c3d/",
            "clip_feat": "XXX/VLCAP/data/anet/anet_clip_b16/lang_feature/",
            "sent_feat": "XXX/VLCAP/data/anet/anet_clip_b16/sent_feature/"
        },
        "yc2": {
            "env_feat": "XXX/VLCAP/data/yc2/yc2_c3d/",
            "clip_feat": "XXX/VLCAP/data/yc2/yc2_clip_b16/lang_feature/",
            "sent_feat": "XXX/VLCAP/data/yc2/yc2_clip_b16/sent_feature/"
        }
    }
``` 
and now my VLCAP folder directory is as follows:
├── cache
├── data
│   └── anet
│       ├── anet_clip_b16
│       │   ├── lang_feature
│       │   └── sent_feature
│       └── env_c3d
├── densevid_eval
│   ├── anet_data
│   ├── coco-caption
│   │   ├── annotations
│   │   ├── pycocoevalcap
│   │   │   ├── bleu
│   │   │   │   └── __pycache__
│   │   │   ├── cider
│   │   │   │   └── __pycache__
│   │   │   ├── meteor
│   │   │   │   ├── data
│   │   │   │   └── __pycache__
│   │   │   ├── __pycache__
│   │   │   ├── rouge
│   │   │   │   └── __pycache__
│   │   │   └── tokenizer
│   │   │       └── __pycache__
│   │   └── pycocotools
│   └── yc2_data
├── results
├── scripts
├── src
│   ├── __pycache__
│   └── rtransformer
│       └── __pycache__
└── video_feature
Thank you! :)

**Comment by Kashu7100** [comment]
Unless it is a full path, maybe you don't need "XXX/VLCAP/" in your path.

**Comment by JiangTianyu51147** [comment]
This error is finally solved and it really is a path error.I changed the path and it is running now.Once again sincerely thank you! :):):)
