### ISSUE TITLE
YouCook2 Features

### ISSUE THREAD

**Issue by yueyue0401** [UARK-AICV/VLCAP#9]
Is it possible to provide the YouCook2 features? Or could you provide the script/code to extract features from the YouCook2 dataset or the configuration of C3D/Clip_b16? 

Thank you so much for the fantastic code!

**Comment by Kashu7100** [comment]
Thanks for your interest!

Could you refer to https://github.com/UARK-AICV/VLCAP/issues/2?

**Comment by Kashu7100** [comment]
@yueyue0401 
We publish the code for our new work: https://github.com/UARK-AICV/VLTinT
In the repo, there are more details about how to extract features. I hope this is helpful to you.
